# Generated by Django 4.0.4 on 2022-05-17 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=200)),
                ('project', models.CharField(default='', max_length=200)),
                ('is_manager', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('married', models.BooleanField(default=False)),
                ('child_quantity', models.IntegerField(default=0)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_finish', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
