# Generated by Django 4.0.4 on 2022-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=100)),
                ('date_birth', models.DateField(default='')),
                ('wife_name', models.CharField(default='', max_length=200)),
                ('child_quantity', models.PositiveIntegerField(default=0)),
                ('children_names', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
