# Generated by Django 4.0.1 on 2022-05-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager_fk',
        ),
        migrations.RemoveField(
            model_name='event',
            name='manager_two_fk',
        ),
    ]
