# Generated by Django 4.0.1 on 2022-06-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_remove_event_manager_fk_remove_event_manager_two_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('in_review', 'Created')], default='In_review', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick leave')], max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_fk',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.project'),
        ),
    ]
