# Generated by Django 4.0.1 on 2022-06-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_project_alter_event_status_alter_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
