# Generated by Django 4.0.1 on 2022-06-11 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0006_remove_profile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984)], verbose_name='year')),
                ('new_year', models.DateField(blank=True, null=True)),
                ('christmas', models.DateField(blank=True, null=True)),
                ('women_day', models.DateField(blank=True, null=True)),
                ('easter', models.DateField(blank=True, null=True)),
                ('labor_day', models.DateField(blank=True, null=True)),
                ('victory_day', models.DateField(blank=True, null=True)),
                ('trinity', models.DateField(blank=True, null=True)),
                ('constitution_day', models.DateField(blank=True, null=True)),
                ('independence_day', models.DateField(blank=True, null=True)),
                ('defenders_day', models.DateField(blank=True, null=True)),
                ('сatholic_сhristmas', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
