# Generated by Django 4.0.1 on 2022-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_alter_event_description_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approve_description',
            field=models.TextField(null=True),
        ),
    ]
